#!/usr/bin/env python3
from os.path import abspath
from os.path import dirname
from os.path import join
import os
import sys
import threading


BASE_DIR = abspath(join(dirname(__file__)))
os.chdir(BASE_DIR)

REPOSITORIES = [
    {'url': "git@bitbucket.org:sousouindustries/sovereign-charter"},
    {'url': "git@github.com:sousouindustries/python-s42"},
    {'url': "git@github.com:sousouindustries/python-stomp"},
    {'url': "git@github.com:sousouindustries/python-es"},
    {'url': "git@github.com:sousouindustries/python-eda"},
    {'url': "git@github.com:sousouindustries/python-libsousou"},
    {'url': "git@github.com:sousouindustries/python-libsovereign"},
    {'url': "git@github.com:sousouindustries/fulcrum-common"},
    {'url': "git@github.com:sousouindustries/fulcrum-mds"},
    {'url': "git@github.com:sousouindustries/fulcrum-rest"},
    {'url': "git@github.com:sousouindustries/aorta-common"},
    {'url': "git@github.com:sousouindustries/aorta-server"},
    {'url': "git@bitbucket.org:sousouindustries/fulcrum"},
    {'url': "git@github.com:sousouindustries/sovereign-infra-common"},
    {'url': "git@github.com:sousouindustries/python-aorta"},
    {'url': "git@github.com:sousouindustries/gateway"},
]


if __name__ == '__main__':
    threads = []
    src_dir = join(BASE_DIR, 'src')

    os.makedirs(src_dir, exist_ok=True)
    for repository in REPOSITORIES:
        url = repository['url']
        name = repository.get('name')
        if name is None:
            name = url.rsplit('/')[-1]

        dst = join(src_dir, name)
        if not os.path.exists(dst):
            print("Cloning to", dst)
            f = lambda: os.system("cd src && git clone " + url)
        else:
            print("Updating", url)
            f = lambda: os.system("cd {0} && git pull origin master".format(dst))
        threads.append(threading.Thread(target=f))
        threads[-1].start()

    # Wait until all threads are finished.
    while threads:
        t = threads.pop(0)
        t.join()
